const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;
const MAX_PAGE = 20;
const seedStores = [
 {id:101,name:'老街炭火烧烤',distance:380,match:96,tags:['烧烤','夜宵','肉食'],lat:30.94,lng:118.75},
 {id:102,name:'巷口牛肉面',distance:620,match:94,tags:['牛肉','面食','午餐'],lat:30.945,lng:118.755},
 {id:103,name:'红房子小吃',distance:820,match:92,tags:['酸辣','小吃','夜宵'],lat:30.938,lng:118.748},
 {id:104,name:'热辣火锅',distance:1200,match:89,tags:['火锅','聚餐','鲜'],lat:30.95,lng:118.76},
 {id:105,name:'甜甜研究所',distance:1500,match:76,tags:['甜品','下午茶','甜'],lat:30.952,lng:118.745},
 {id:106,name:'阿强炒饭',distance:900,match:96,tags:['米饭','牛肉','性价比'],lat:30.942,lng:118.752}
];
const seedDishes = [
 {id:1,name:'爆汁烤五花',storeId:101,store:'老街炭火烧烤',price:28,match:97,likes:928,tags:['咸香','酥脆','爆汁','烧烤','肉食','夜宵']},
 {id:2,name:'招牌牛肉面',storeId:102,store:'巷口牛肉面',price:18,match:94,likes:726,tags:['咸鲜','牛肉','面食','劲道','碳水','午餐']},
 {id:3,name:'酸辣粉',storeId:103,store:'红房子小吃',price:12,match:92,likes:613,tags:['酸辣','爽滑','小吃','夜宵','重口']},
 {id:4,name:'招牌虾滑',storeId:104,store:'热辣火锅',price:39,match:89,likes:542,tags:['鲜','Q弹','火锅','聚餐','高蛋白']},
 {id:5,name:'黑糖麻薯',storeId:105,store:'甜甜研究所',price:16,match:76,likes:481,tags:['甜','软糯','下午茶','甜品']},
 {id:6,name:'锅气牛肉炒饭',storeId:106,store:'阿强炒饭',price:15,match:96,likes:804,tags:['咸香','锅气','牛肉','米饭','性价比']}
];
const TAG_GROUPS={taste:['甜','酸','辣','麻','咸','鲜','清淡','咸香','酸辣','麻辣','酱香','奶香','蒜香','果香'],texture:['酥脆','Q弹','软糯','爽脆','滑嫩','爆汁','绵密','扎实','嫩','焦香'],ingredient:['牛肉','猪肉','鸡肉','鸭肉','海鲜','蔬菜','面食','米饭','奶制品','水果','甜品'],scene:['一个人吃','情侣约会','朋友聚餐','家庭聚餐','打工人午餐','下午茶','夜宵','生日','带娃','聚会']};
function openid(){return cloud.getWXContext().OPENID} function now(){return db.serverDate()} function clamp(n,a=0,b=99){return Math.max(a,Math.min(b,n))}
function score(d,taste=[]){const s=new Set(taste||[]),tags=d.tags||[],hit=tags.filter(x=>s.has(x)).length;return clamp(Math.round((d.match||70)*.6+(hit/Math.max(tags.length,1))*40),40,99)}
function page(e){return Math.max(1,Number(e.page)||1)}
async function ensureSeeds(){if(!(await db.collection('dishes').limit(1).get()).data.length)for(const x of seedDishes)await db.collection('dishes').add({data:x});if(!(await db.collection('stores').limit(1).get()).data.length)for(const x of seedStores)await db.collection('stores').add({data:x})}
function distance(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,A=Math.sin(r(c-a)/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(r(d-b)/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(A),Math.sqrt(1-A)))}
async function profile(id){return (await db.collection('users').doc(id).get().catch(()=>({data:{}}))).data||{}}
async function ensureUser(id){await db.collection('users').doc(id).set({data:{_id:id,updatedAt:now()},merge:true}).catch(()=>{})}
exports.main=async(e)=>{const action=e.action,me=openid();try{await ensureUser(me);
if(action==='login')return{success:true,openid:me,data:await profile(me)};
if(action==='seed'){await ensureSeeds();return{success:true}};
if(action==='getDishes'){await ensureSeeds();let q=db.collection('dishes');if(e.storeId)q=q.where({storeId:Number(e.storeId)});const r=await q.skip((page(e)-1)*MAX_PAGE).limit(MAX_PAGE).get();return{success:true,data:r.data}};
if(action==='getDish'){await ensureSeeds();const r=await db.collection('dishes').where({id:Number(e.id)}).limit(1).get();return{success:true,data:r.data[0]||seedDishes.find(x=>x.id===Number(e.id))}};
if(action==='getStores'){await ensureSeeds();const r=await db.collection('stores').skip((page(e)-1)*MAX_PAGE).limit(MAX_PAGE).get();return{success:true,data:r.data.length?r.data:seedStores}};
if(action==='search'){await ensureSeeds();const q=String(e.keyword||'').trim().toLowerCase();if(!q)return{success:true,dishes:[],stores:[]};const[d,s]=await Promise.all([db.collection('dishes').limit(100).get(),db.collection('stores').limit(100).get()]),hit=x=>(x.name+' '+(x.store||'')+' '+(x.tags||[]).join(' ')).toLowerCase().includes(q);return{success:true,dishes:d.data.filter(hit).slice(0,20),stores:s.data.filter(hit).slice(0,20)}};
if(action==='action'){const dishId=Number(e.dishId),type=String(e.type||'yes');if(!dishId||!['yes','conditional','no','none','eat','eatAgain'].includes(type))return{success:false,message:'无效操作'};const old=await db.collection('user_actions').where({openid:me,dishId}).limit(1).get();if(type==='none'){if(old.data.length)await db.collection('user_actions').doc(old.data[0]._id).remove();return{success:true,type:'none'}}const data={openid:me,dishId,type,updatedAt:now()};if(old.data.length)await db.collection('user_actions').doc(old.data[0]._id).update({data});else await db.collection('user_actions').add({data});return{success:true,type}};
if(action==='favorite'){const dishId=Number(e.dishId);if(!dishId)return{success:false,message:'无效菜品'};const old=await db.collection('favorites').where({openid:me,dishId}).limit(1).get();if(old.data.length)await db.collection('favorites').doc(old.data[0]._id).remove();else await db.collection('favorites').add({data:{openid:me,dishId,createdAt:now()}});return{success:true,favorited:!old.data.length}};
if(action==='comment'){const content=String(e.content||'').trim().slice(0,500),bad=['赌博','诈骗','色情','辱骂'];if(!content)return{success:false,message:'评论不能为空'};if(content.length<2)return{success:false,message:'评论至少2个字'};if(bad.some(x=>content.includes(x)))return{success:false,message:'评论包含敏感内容'};const r=await db.collection('comments').add({data:{openid:me,dishId:Number(e.dishId),postId:e.postId||'',parentId:e.parentId||'',content,likes:0,createdAt:now()}});return{success:true,id:r._id}};
if(action==='comments'){const r=await db.collection('comments').where({dishId:Number(e.dishId),parentId:e.parentId||''}).orderBy('createdAt','desc').skip((page(e)-1)*MAX_PAGE).limit(MAX_PAGE).get();return{success:true,data:r.data}};
if(action==='commentLike'){const id=e.commentId,old=await db.collection('comment_likes').where({openid:me,commentId:id}).limit(1).get();if(old.data.length){await db.collection('comment_likes').doc(old.data[0]._id).remove();await db.collection('comments').doc(id).update({data:{likes:_.inc(-1)}})}else{await db.collection('comment_likes').add({data:{openid:me,commentId:id,createdAt:now()}});await db.collection('comments').doc(id).update({data:{likes:_.inc(1)}})}return{success:true,liked:!old.data.length}};
if(action==='follow'){const targetId=String(e.targetId||'');if(!targetId||targetId===me)return{success:false,message:'无效用户'};const old=await db.collection('follows').where({openid:me,targetId}).limit(1).get();if(old.data.length)await db.collection('follows').doc(old.data[0]._id).remove();else await db.collection('follows').add({data:{openid:me,targetId,createdAt:now()}});return{success:true,following:!old.data.length}};
if(action==='setTaste'){const taste=Array.isArray(e.taste)?e.taste.slice(0,30):[],tags=Array.isArray(e.tags)?e.tags.slice(0,10):taste.slice(0,3);await db.collection('users').doc(me).set({data:{taste,tags,updatedAt:now()},merge:true});return{success:true,data:{taste,tags}}};
if(action==='publish'){const dish=String(e.dish||'').trim().slice(0,100),store=String(e.store||'').trim().slice(0,100);if(!dish)return{success:false,message:'菜品名称不能为空'};const r=await db.collection('posts').add({data:{openid:me,name:dish,store,storeId:Number(e.storeId)||0,image:e.image||'',tags:Array.isArray(e.tags)?e.tags.slice(0,10):[],vote:['yes','conditional','no'].includes(e.vote)?e.vote:'yes',note:String(e.note||'').slice(0,1000),likes:0,comments:0,createdAt:now()}});await db.collection('users').doc(me).set({data:{posts:_.inc(1),exp:_.inc(20),updatedAt:now()},merge:true});return{success:true,id:r._id}};
if(action==='feed'){const r=await db.collection('posts').orderBy('createdAt','desc').skip((page(e)-1)*MAX_PAGE).limit(MAX_PAGE).get();return{success:true,data:r.data}};
if(action==='sameHobby'){const u=await profile(me),mine=new Set([...(u.taste||[]),...(u.tags||[])]),users=(await db.collection('users').limit(100).get()).data.filter(x=>x._id!==me).map(x=>{const t=new Set([...(x.taste||[]),...(x.tags||[])]),common=[...mine].filter(v=>t.has(v));return{...x,similarity:clamp(Math.round(common.length/Math.max(1,mine.size)*100),50,99),common}}).sort((a,b)=>b.similarity-a.similarity).slice(0,20);return{success:true,data:users}};
if(action==='hobbyDetail'){const u=await profile(String(e.userId)),m=await profile(me),a=new Set([...(m.taste||[]),...(m.tags||[])]),b=new Set([...(u.taste||[]),...(u.tags||[])]);return{success:true,data:{...u,similarity:clamp(Math.round([...a].filter(x=>b.has(x)).length/Math.max(1,a.size)*100),50,99),common:[...a].filter(x=>b.has(x))}}};
if(action==='recommend'){await ensureSeeds();const u=await profile(me),taste=Array.isArray(e.taste)?e.taste:u.taste||[],a=(await db.collection('user_actions').where({openid:me}).limit(1000).get()).data,liked=new Set(a.filter(x=>x.type==='yes').map(x=>x.dishId)),all=(await db.collection('dishes').limit(100).get()).data,data=all.filter(x=>!liked.has(x.id)).map(x=>({...x,match:score(x,taste),reason:`命中你的${(x.tags||[]).filter(t=>taste.includes(t)).slice(0,3).join('、')||'口味偏好'}`})).sort((a,b)=>b.match-a.match).slice(0,10);return{success:true,data}};
if(action==='recommendReason'){const r=await db.collection('dishes').where({id:Number(e.dishId)}).limit(1).get(),dish=r.data[0]||seedDishes.find(x=>x.id===Number(e.dishId)),u=await profile(me),common=(dish?.tags||[]).filter(x=>(u.taste||[]).includes(x));return{success:true,data:{score:score(dish||{},u.taste||[]),common,reason:common.length?`你喜欢的${common.join('、')}都命中啦`:'这道菜与你近期探索的口味方向接近'}}};
if(action==='profile'){const u=await profile(me),a=(await db.collection('user_actions').where({openid:me}).limit(1000).get()).data,p=(await db.collection('posts').where({openid:me}).limit(1000).get()).data,exp=u.exp||0;return{success:true,data:{...u,likes:a.filter(x=>x.type==='yes').length,actions:a.length,posts:p.length,level:Math.min(6,1+Math.floor(exp/100)),exp}}};
if(action==='badges'){const u=await profile(me),a=(await db.collection('user_actions').where({openid:me}).limit(1000).get()).data,p=(await db.collection('posts').where({openid:me}).limit(1000).get()).data,n=a.filter(x=>x.type==='yes').length;return{success:true,data:[{id:'first',name:'第一口',icon:'🍽️',unlocked:n>=1},{id:'hundred',name:'百味尝鲜',icon:'💯',unlocked:n>=100},{id:'night',name:'夜猫子',icon:'🌙',unlocked:a.filter(x=>x.type==='eat'||x.type==='eatAgain').length>=10},{id:'recommend',name:'推荐达人',icon:'🔥',unlocked:p.length>=10},{id:'local',name:'本地通',icon:'📍',unlocked:p.length>=30},{id:'master',name:'许吃大师',icon:'👑',unlocked:(u.exp||0)>=500}]}};
if(action==='nearby'){await ensureSeeds();const lat=Number(e.lat),lng=Number(e.lng),hasLocation=Number.isFinite(lat)&&Number.isFinite(lng)&&lat!==0&&lng!==0,stores=(await db.collection('stores').limit(100).get()).data,data=stores.map(s=>({...s,distance:hasLocation&&s.lat!=null&&s.lng!=null?distance(lat,lng,s.lat,s.lng):s.distance})).sort((a,b)=>a.distance-b.distance);return{success:true,data}};
if(action==='aiAnalyze'){const text=String(e.text||''),tags=[];for(const list of Object.values(TAG_GROUPS))for(const t of list)if(text.includes(t))tags.push(t);if(text.includes('牛肉'))tags.push('牛肉');if(text.includes('烤'))tags.push('烧烤');return{success:true,data:{dishName:e.dishName||'',tags:[...new Set(tags)].slice(0,10),confidence:tags.length?.92:.65}}};
if(action==='claimStore'){const storeId=Number(e.storeId);if(!storeId)return{success:false,message:'无效店铺'};const old=await db.collection('merchant_claims').where({storeId,openid:me}).limit(1).get();if(old.data.length)return{success:true,status:'pending'};await db.collection('merchant_claims').add({data:{storeId,openid:me,status:'pending',createdAt:now()}});return{success:true,status:'pending'}};
if(action==='merchantData'){const storeId=Number(e.storeId),[d,p,a]=await Promise.all([db.collection('dishes').where({storeId}).limit(100).get(),db.collection('posts').where({storeId}).limit(1000).get(),db.collection('user_actions').limit(1000).get()]),ids=new Set(d.data.map(x=>x.id)),acts=a.data.filter(x=>ids.has(x.dishId));return{success:true,data:{dishes:d.data.length,posts:p.data.length,yes:acts.filter(x=>x.type==='yes').length,conditional:acts.filter(x=>x.type==='conditional').length,no:acts.filter(x=>x.type==='no').length}}};
return{success:false,message:'未知操作'};
}catch(err){console.error(err);return{success:false,message:'服务暂时不可用',error:err.message}}};
